version: "3.8"
services:
  # Config Server Replica Set
  config1:
    image: mongo
    container_name: config1
    command: --configsvr --replSet configReplSet --port 28017
    ports:
      - "28017:28017"
    volumes:
      - config1data:/data/db
    networks:
      - mongocluster

  config2:
    image: mongo
    container_name: config2
    command: --configsvr --replSet configReplSet --port 28018
    ports:
      - "28018:28018"
    volumes:
      - config2data:/data/db
    networks:
      - mongocluster

  config3:
    image: mongo
    container_name: config3
    command: --configsvr --replSet configReplSet --port 28019
    ports:
      - "28019:28019"
    volumes:
      - config3data:/data/db
    networks:
      - mongocluster

  # Shard Replica Set
  shard1:
    image: mongo
    container_name: shard1
    command: --shardsvr --replSet shardReplSet --port 27021
    ports:
      - "27021:27021"
    volumes:
      - shard1data:/data/db
    networks:
      - mongocluster

  shard2:
    image: mongo
    container_name: shard2
    command: --shardsvr --replSet shardReplSet --port 27022
    ports:
      - "27022:27022"
    volumes:
      - shard2data:/data/db
    networks:
      - mongocluster

  shard3:
    image: mongo
    container_name: shard3
    command: --shardsvr --replSet shardReplSet --port 27023
    ports:
      - "27023:27023"
    volumes:
      - shard3data:/data/db
    networks:
      - mongocluster

  # Mongos Router
  mongos:
    image: mongo
    container_name: mongos
    command: mongos --configdb configReplSet/config1:28017,config2:28018,config3:28019 --port 27020
    ports:
      - "27020:27020"
    networks:
      - mongocluster

volumes:
  config1data:
  config2data:
  config3data:
  shard1data:
  shard2data:
  shard3data:

networks:
  mongocluster: